### ISSUE TITLE
Missing script parts here

### ISSUE THREAD

**Issue by marckerr** [jamfprofessionalservices/CIS-for-macOS-Sierra-CP#1]
https://github.com/jamfprofessionalservices/CIS-for-macOS-Sierra-CP/blob/c6ff8007693d7a8ba6322b63db70b3b14aa8c9d1/CIS%20Scripts/2_Security_Audit_Compliance_ORG.sh#L1226

add
		echo "* 5.7 Do Not enable the "root" account" >> "$auditfilelocation"
        echo $(date -u) "5.7 fix" | tee -a "$logFile"

**Comment by erinmc** [comment]
Hey there!  

Thanks very much for catching this.  Will be making the change to this today.

**Comment by erinmc** [comment]
Added logging for remediation of 5.7
